language: go
sudo: false
go:
  - 1.7.3
  - tip
env:
  global:
    - GOARCH=amd64

before_install:
 - go get github.com/9corp/9volt
 - go get github.com/tools/godep
 - go get github.com/onsi/ginkgo/ginkgo
 - go get github.com/onsi/gomega

install:

script:
  - go test -v ./...
