language: go

sudo: required

services:
  - docker

go:
  - 1.7.3
  - 1.8.x
  - tip

env:
  global:
    - GOARCH=amd64
    - SEMVER=$TRAVIS_TAG
    - secure: Il7PicfxW3e4jBPlK+be0P96uQA2i5FPyqaUCaQrsXhLZJe9VLbD4MJAiq7jZftDN2PD6CvzgafqRHK/mqwe48rpgAA7pCENnANE6nQXVROPK1EfiuwYbrqz7eIkV5UlN83daRZZuq/UVTUsbPBF8w74NUeuVcygiSO4drasuM418Us3UK803ZBzV6xRArqTu+tbZqjnwmMBQFb8qwHc9/D+i0IOL8kkBTvQyn9wgaU2sbXiRJtAnij/p2npJhzPbTIXpkkas/TnRb11Sn6vIiBoPnV60cJCwL6Z2NKXZzfU+2ZWqmX8JnnIBZdMXvSnVVRga63qq874z4Qv+KqjWpnwwb/fMVYuYDAfYNLp/uRVcJLezp8VJS7q5O+Js9ehujQCEUdxzxv1lYeRCO+zKmbgR1QlYzK+fgUHTFw8I2MKJ/Pgeb3QFRkxwwc3SIN6TARYRuIBpwOWlrEsip24Y8LAUWsz4GH+PQVYYuqJK5+jlvqDIwHz/M9hp1szuNklID66UPaba8TkArAaSY9F99DrkcTDtXa69ItyAgBce6lUiwKfgnD8QUkg8457sbsCmLyz2hQlq5p03D2QksdEVgWOnHQAgxP8zQIBaXy31n9I6UwiY27+LshkUCQ4blD0ffUkiNG45/m+VVEjifxCq0LbaHVi/plnh3ljFj5O4n8= # DOCKER_EMAIL
    - secure: oZhhir66EMV+4VhF4wSlhMfJv16ix9Am4wLt/mDElWndFfo5SmtGRWdoec9oxGBMMzHjNQYkIZOHUno7xUDA4LH3RJhLGBOw+ns0qiN6GQmBXoAq9N5GnPwx63T5ESVyHNN35h/QCAlJp/jj0HTmSMFlHnzeOiHsY1akYyoqsV3GP+xDOHm7mb1OErE9NnMSGqwVWmbsQ1knvNYaw+AAogS6Ol594X8d5DM9dqZVKq5TXHruXFJy1pz3GFI6TCqU38BQu8JiiNcKev1wzS5Cmnd8mHbhz8hV2U9Rhg7BLLPr4Z5MXjrnpkDihjpOG5uxK1N1odG60ec5hhDfdUPNdZxpEv6lE12e+2YlP/nGbikmObpbG77YeJm/JpJExaq7Ke2cr2FHyCpLPdKd+rVVFTaKkRmsZTuQri/B6LFx2x7v4G+96K6F6KGTgFGkkQMSxyhQCa+yE6mfPwjwNkZaZ4qepNGratLJ9VtkdkmvOi/nnpcsJXwYBPszKQXcLbbjWvd9PJcSAK+ZbG8zdNhDHRvBvkw9P6piXsAG9GQQ88mdqcuP3QamQsFYU2ZjjnEu9TyhNOsW8AjtgaCaNyotwdy4hPcA5OE/8KtQb1SaCzqTtXUJDYcnjAqjifMSAEtUwzKnMLZkeu4fG1AV5w9EfLFWKcrg4hHbQM6F9luT/Jc= # DOCKER_USER
    - secure: FhneVKmAcGUqKRtg5pFDKxNmt1a8yM6V4bl5TvZiFfbPHxYBpwBq+9EZ+UFE96UnTbc+mKGgLpWbQoN3hZDlSmP/oKB2ED49O0pKtiWDdywPFf+lv/53TJ6np71chBLKWq0yMyHtcSMhFe2J9GyYLpCYNhkW2+VXUe2Bcyf6msypyk2hISOJnrUCKdhwro2D8HVGKZWovfIvUIQ2CCG/mcb4xrrmoxvzt+hq4EFj9zzX4ocfwl+7+1RozOuBHvIAA1o1z3qJ2tFbn1BXyoeN082N5yuacDlqM6SOSa1206/ZRd7v+q34ZFCP2YCA45pDfpcpxll5jOk4cOCFxsrQ0c9OwKflNVvyr0puqqdRK+d76jGkZ0KZas9ASkNdNmnc/Rvm4LUjH5bpoUeVCVvsAL3bEWYT7J7Y4S+iyiuRqHl2eFq2IwomAhospdBQ9dagL1uK5vnAAbGSzcMvM+7nRiaug2WgDDG+rleDR+Q6/K0RRfYHJEXux60JOmPiOu2h0dkAyI2lWpkga5P7VzH5j91aN3BON7rW49bwSK/hLbN6TkzRO6Oa45bEkaWLGy9iyav49ceJJK04MqoFHkg/bvoX7c97IAvvVCCNz6Yaakq4A6mUoKuZ2ro21dq4LYfIhwYPQrqCC1Pi25HP3+Pq1fzqe9bcbSgLzK8gS+0Ct9s= # DOCKER_PASS
script:
  - make test

before_deploy: make build/release-travis

deploy:
  provider: releases
  api_key:
    secure: sAR3Zz2f1wA8n6/gakAEjns9FF33m1168sagF+M8wSzZJjAMiIQ5dU0cQ/l9noLNag32mRljMy+Hr586DmKlaciQsXHn0AlQlybZs0mEL5xPQDKrsb4/CVbNCFWyjZnNEVZ0p/zF05pm96OVnFtTGN3eNIrHTT761x881Y3WaHQDhF0OIRraIslgNaZCwXp3MZ8CIzn9Sdf9Zt2YflF28oGkfjVsXrsvSaMPrY4mD05H6nuVXfqftaiFT+2BBg7TQ74RwUzkqF5abcqn3LsL9WvHoFC9GizFbbWt1W8EzUBF3NjbIS461wn1ksNWcEYRncF4nA3VEr3SyTuh1Q+sv3AqkDaxe35/dIpX3q5ymuL4+wGAZeB5BHcQ6e1LXMeHB846aFZAtAqnzb28yKjDJTsBjBf/y1vSisXAhvQly1sXlebDihEPHrQF1+pUTVMmNmYGtSpI1ZW5EMucnZKPVYMIeuS+pRwtwFOuKMS/8Z+9+xUCQ6WDApCdK531FDCXKEg4hdxJcJUSUwB5qMlUIZkr7+kL6Vp2s26J+iaus21+1nVJB4ao1EhB6InE8V5vS9oCLnowxqr+X/boCizB22vTvLbW/JDP0oSAurmvmOZ2v8REAAgfB5aqGhU5EAGQxciCwVkQT1I/8hQ8ODNmF+z6r1PGsDQWziaDb+4Rs7A=
  file:
    - "build/9volt-$TRAVIS_TAG-darwin.tgz"
    - "build/9volt-$TRAVIS_TAG-linux.tgz"
  on:
    tags: true

after_deploy:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t "9corp/9volt:$SEMVER" -t "9corp/9volt:latest" .
  - docker push 9corp/9volt:$SEMVER
  - docker push 9corp/9volt:latest
