// This file was generated by counterfeiter
package eventfakes

import (
	"sync"

	"github.com/9corp/9volt/event"
	log "github.com/Sirupsen/logrus"
)

type FakeIClient struct {
	AddStub        func(string, string) error
	addMutex       sync.RWMutex
	addArgsForCall []struct {
		arg1 string
		arg2 string
	}
	addReturns struct {
		result1 error
	}
	addReturnsOnCall map[int]struct {
		result1 error
	}
	AddWithErrorLogStub        func(string, log.FieldLogger, log.Fields) error
	addWithErrorLogMutex       sync.RWMutex
	addWithErrorLogArgsForCall []struct {
		arg1 string
		arg2 log.FieldLogger
		arg3 log.Fields
	}
	addWithErrorLogReturns struct {
		result1 error
	}
	addWithErrorLogReturnsOnCall map[int]struct {
		result1 error
	}
	AddWithLogStub        func(string, string, log.FieldLogger, log.Fields) error
	addWithLogMutex       sync.RWMutex
	addWithLogArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 log.FieldLogger
		arg4 log.Fields
	}
	addWithLogReturns struct {
		result1 error
	}
	addWithLogReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeIClient) Add(arg1 string, arg2 string) error {
	fake.addMutex.Lock()
	ret, specificReturn := fake.addReturnsOnCall[len(fake.addArgsForCall)]
	fake.addArgsForCall = append(fake.addArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("Add", []interface{}{arg1, arg2})
	fake.addMutex.Unlock()
	if fake.AddStub != nil {
		return fake.AddStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.addReturns.result1
}

func (fake *FakeIClient) AddCallCount() int {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	return len(fake.addArgsForCall)
}

func (fake *FakeIClient) AddArgsForCall(i int) (string, string) {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	return fake.addArgsForCall[i].arg1, fake.addArgsForCall[i].arg2
}

func (fake *FakeIClient) AddReturns(result1 error) {
	fake.AddStub = nil
	fake.addReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIClient) AddReturnsOnCall(i int, result1 error) {
	fake.AddStub = nil
	if fake.addReturnsOnCall == nil {
		fake.addReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIClient) AddWithErrorLog(arg1 string, arg2 log.FieldLogger, arg3 log.Fields) error {
	fake.addWithErrorLogMutex.Lock()
	ret, specificReturn := fake.addWithErrorLogReturnsOnCall[len(fake.addWithErrorLogArgsForCall)]
	fake.addWithErrorLogArgsForCall = append(fake.addWithErrorLogArgsForCall, struct {
		arg1 string
		arg2 log.FieldLogger
		arg3 log.Fields
	}{arg1, arg2, arg3})
	fake.recordInvocation("AddWithErrorLog", []interface{}{arg1, arg2, arg3})
	fake.addWithErrorLogMutex.Unlock()
	if fake.AddWithErrorLogStub != nil {
		return fake.AddWithErrorLogStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.addWithErrorLogReturns.result1
}

func (fake *FakeIClient) AddWithErrorLogCallCount() int {
	fake.addWithErrorLogMutex.RLock()
	defer fake.addWithErrorLogMutex.RUnlock()
	return len(fake.addWithErrorLogArgsForCall)
}

func (fake *FakeIClient) AddWithErrorLogArgsForCall(i int) (string, log.FieldLogger, log.Fields) {
	fake.addWithErrorLogMutex.RLock()
	defer fake.addWithErrorLogMutex.RUnlock()
	return fake.addWithErrorLogArgsForCall[i].arg1, fake.addWithErrorLogArgsForCall[i].arg2, fake.addWithErrorLogArgsForCall[i].arg3
}

func (fake *FakeIClient) AddWithErrorLogReturns(result1 error) {
	fake.AddWithErrorLogStub = nil
	fake.addWithErrorLogReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIClient) AddWithErrorLogReturnsOnCall(i int, result1 error) {
	fake.AddWithErrorLogStub = nil
	if fake.addWithErrorLogReturnsOnCall == nil {
		fake.addWithErrorLogReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addWithErrorLogReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIClient) AddWithLog(arg1 string, arg2 string, arg3 log.FieldLogger, arg4 log.Fields) error {
	fake.addWithLogMutex.Lock()
	ret, specificReturn := fake.addWithLogReturnsOnCall[len(fake.addWithLogArgsForCall)]
	fake.addWithLogArgsForCall = append(fake.addWithLogArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 log.FieldLogger
		arg4 log.Fields
	}{arg1, arg2, arg3, arg4})
	fake.recordInvocation("AddWithLog", []interface{}{arg1, arg2, arg3, arg4})
	fake.addWithLogMutex.Unlock()
	if fake.AddWithLogStub != nil {
		return fake.AddWithLogStub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.addWithLogReturns.result1
}

func (fake *FakeIClient) AddWithLogCallCount() int {
	fake.addWithLogMutex.RLock()
	defer fake.addWithLogMutex.RUnlock()
	return len(fake.addWithLogArgsForCall)
}

func (fake *FakeIClient) AddWithLogArgsForCall(i int) (string, string, log.FieldLogger, log.Fields) {
	fake.addWithLogMutex.RLock()
	defer fake.addWithLogMutex.RUnlock()
	return fake.addWithLogArgsForCall[i].arg1, fake.addWithLogArgsForCall[i].arg2, fake.addWithLogArgsForCall[i].arg3, fake.addWithLogArgsForCall[i].arg4
}

func (fake *FakeIClient) AddWithLogReturns(result1 error) {
	fake.AddWithLogStub = nil
	fake.addWithLogReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeIClient) AddWithLogReturnsOnCall(i int, result1 error) {
	fake.AddWithLogStub = nil
	if fake.addWithLogReturnsOnCall == nil {
		fake.addWithLogReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addWithLogReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeIClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	fake.addWithErrorLogMutex.RLock()
	defer fake.addWithErrorLogMutex.RUnlock()
	fake.addWithLogMutex.RLock()
	defer fake.addWithLogMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeIClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ event.IClient = new(FakeIClient)
